<a href="https://colab.research.google.com/github/Antonio-Kishore/Day1_ML/blob/main/Day1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [2]:
# Mathematical Operations
import numpy as np
a=[1,2,3,4,5]
arr1=np.array(a)
b=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(b)
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [4]:
print(type(a),
type(arr1),
type(b),
type(arr2))

<class 'list'> <class 'numpy.ndarray'> <class 'list'> <class 'numpy.ndarray'>


In [6]:
import sys
s= range(1000)
print("Size of each element in the list in bytes", sys.getsizeof(s))
print("Complete list size in bytes",sys.getsizeof(s)*len(s))


Size of each element in the list in bytes 48
Complete list size in bytes 48000


In [8]:
#We are Checking comparison between numpy size and normal size of "sys" package
import numpy as np
s=np.arange(1000)
print("Size of each element in the list by bytes",s.itemsize)
print("Complete list size in bytes",s.size * s.itemsize)

Size of each element in the list by bytes 8
Complete list size in bytes 8000


In [9]:
#Import time library and make execution time taking by the system
import time
a= range(1000)
b=range(1000)
start = time.time()
ab=[(a*b) for a,b in zip(a,b)]
end=time.time()
print("Total time taken", end-start)

Total time taken 0.00017070770263671875


In [13]:
import numpy
arr1=np.arange(1000)
arr2=np.arange(1000)
start=time.time()
arr_mul=arr1*arr2
end=time.time()
print("Total time taken",end-start)

Total time taken 4.553794860839844e-05


In [14]:
lst1=[1,2,3,4]
arr=np.array(lst1)
print(arr)

[1 2 3 4]
